code/force-app/main/default/objects/FinServ__AccountAccountRelation__c/FinServ__AccountAccountRelation__c.object-meta.xml
<CustomObject>
    <description>A relationship between two accounts, such as a household and a business account.</description>
    <label>Account-Account Relationship</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Account Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Account Relations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

code/force-app/main/default/objects/FinServ__AccountAccountRelation__c/fields/CUB_External_Id__c.field-meta.xml
<CustomField>
    <fullName>CUB_External_Id__c</fullName>
    <description>關係key值，不使用原生FSC package的external id欄位</description>
    <externalId>true</externalId>
    <label>CUB External ID</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

code/force-app/main/default/objects/FinServ__AccountAccountRelation__c/fields/FinServ__InverseRelationship__c.field-meta.xml
<CustomField>
    <fullName>FinServ__InverseRelationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Uniquely identifies the relationship between Account__c and RelatedAccount__c so that it can be referenced by a trigger that creates the inverse relationship record.</description>
    <label>InverseRelationship</label>
    <referenceTo>FinServ__AccountAccountRelation__c</referenceTo>
    <relationshipLabel>Account Account Relations</relationshipLabel>
    <relationshipName>AccountAccountRelations</relationshipName>
    <type>Lookup</type>
</CustomField>

code/force-app/main/default/objects/FinServ__AccountAccountRelation__c/fields/Relation_Record_Key__c.field-meta.xml
<CustomField>
    <fullName>Relation_Record_Key__c</fullName>
    <formula>RecordType.DeveloperName &amp;
TEXT(FinServ__Account__r.Customer_Data_Country__c) &amp; 
TEXT(FinServ__Account__r.Identification_Type__c) &amp; 
FinServ__Account__r.Customer_ID__c &amp;
TEXT(FinServ__RelatedAccount__r.Customer_Data_Country__c) &amp;
TEXT(FinServ__RelatedAccount__r.Identification_Type__c) &amp;
FinServ__RelatedAccount__r.Customer_ID__c &amp;
IF(RecordType.DeveloperName = &quot;RelatedParties&quot;, TEXT(Parties_Code__c), &quot;&quot;) &amp; 
IF(RecordType.DeveloperName = &quot;SupplyChain&quot;, TEXT(FinServ__Role__r.SupplyChain_Type__c), &quot;&quot;) &amp;
IF(RecordType.DeveloperName = &quot;SupplyChain&quot;, Year__c, &quot;&quot;) &amp;
IF(RecordType.DeveloperName = &quot;Affiliate&quot;, 
  IF(INCLUDES(Affiliate_Code__c, &quot;A&quot;), &quot;A&quot;, &quot;&quot;) &amp;
  IF(INCLUDES(Affiliate_Code__c, &quot;B&quot;), &quot;B&quot;, &quot;&quot;) &amp;
  IF(INCLUDES(Affiliate_Code__c, &quot;C&quot;), &quot;C&quot;, &quot;&quot;) 
, &quot;&quot;)</formula>
    <label>關係Key值</label>
    <type>Text</type>
</CustomField>

code/force-app/main/default/classes/AARTriggerHandler.cls
public with sharing class AARTriggerHandler {
    public AARTriggerHandler() {

    }

    public static void setInverseRelationship(Map<Id,FinServ__AccountAccountRelation__c> oldItems, List<FinServ__AccountAccountRelation__c> newLists){
        for(FinServ__AccountAccountRelation__c aar : newLists){
            //此ID 為 特定虛擬ID 換org需更換
            if(aar.FinServ__InverseRelationship__c.equals('a00H3000001FtK5IAK')){
                aar.FinServ__InverseRelationship__c = oldItems.get(aar.Id).FinServ__InverseRelationship__c;
            }
        }
    }

    public static void uiCreateAddExternalId(List<FinServ__AccountAccountRelation__c> newLists){
        for(FinServ__AccountAccountRelation__c aar : newLists){
            aar.CUB_External_Id__c = aar.Relation_Record_Key__c;
        }
    }

}