code/force-app/main/default/objects/User/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>所屬區部</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Unit_Name</valueSetName>
    </valueSet>
</CustomField>

code/force-app/main/default/objects/User/fields/Unit_Name__c.field-meta.xml
<CustomField>
    <fullName>Unit_Name__c</fullName>
    <label>所屬區部名稱</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

code/force-app/main/default/globalValueSets/Unit_Name.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>737</fullName>
        <label>投金區</label>
    </customValue>
    <customValue>
        <fullName>728</fullName>
        <label>產一區</label>
    </customValue>
    <customValue>
        <fullName>722</fullName>
        <label>產二區</label>
    </customValue>
    <customValue>
        <fullName>725</fullName>
        <label>產三區</label>
    </customValue>
    <customValue>
        <fullName>777</fullName>
        <label>北一區</label>
    </customValue>
    <customValue>
        <fullName>721</fullName>
        <label>北二區</label>
    </customValue>
    <customValue>
        <fullName>726</fullName>
        <label>北三區</label>
    </customValue>
    <customValue>
        <fullName>735</fullName>
        <label>北四區</label>
    </customValue>
    <customValue>
        <fullName>729</fullName>
        <label>桃竹區</label>
    </customValue>
    <customValue>
        <fullName>731</fullName>
        <label>中一區</label>
    </customValue>
    <customValue>
        <fullName>779</fullName>
        <label>中二區</label>
    </customValue>
    <customValue>
        <fullName>733</fullName>
        <label>南區台南</label>
    </customValue>
    <customValue>
        <fullName>734</fullName>
        <label>南區高雄</label>
    </customValue>
    <customValue>
        <fullName>604</fullName>
        <label>胡志明市分行</label>
    </customValue>
    <customValue>
        <fullName>605</fullName>
        <label>新加坡分行</label>
    </customValue>
    <customValue>
        <fullName>603</fullName>
        <label>香港分行</label>
    </customValue>
    <masterLabel>區部名稱</masterLabel>
</GlobalValueSet>

code/force-app/main/default/classes/UserTriggerHandler.cls
/*
* Author: IBM
* Date: 2024/07/18
*
* Description: User Trigger Handler used to update a text field with a picklist label value
*/
public inherited sharing class UserTriggerHandler {
    
    public static void UpdateLabelValue(List<User> newUser){
        Map<String, String> unitPicklistMap = new Map<String, String>();
        List<Schema.PicklistEntry> units = Schema.SObjectType.User.fields.Unit__c.getPicklistValues();
        
        for(Schema.PicklistEntry ple :units){
            unitPicklistMap.put(ple.getValue(), ple.getLabel());
        }
        
        for(User u: newUser){
            u.Unit_Name__c = unitPicklistMap.get(u.Unit__c);
        }
    }
}