code/force-app/main/default/objects/Account/fields/Customer_Data_Country__c.field-meta.xml
<CustomField>
    <fullName>Customer_Data_Country__c</fullName>
    <label>客戶資料國別</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CUB_Country</valueSetName>
    </valueSet>
</CustomField>

code/force-app/main/default/objects/Account/fields/Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_ID__c</fullName>
    <externalId>true</externalId>
    <label>客戶 ID</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

code/force-app/main/default/objects/Account/fields/Earliest_NonCredit_Date__c.field-meta.xml
<CustomField>
    <fullName>Earliest_NonCredit_Date__c</fullName>
    <label>非授信戶最早往來日期</label>
    <type>Date</type>
</CustomField>

code/force-app/main/default/objects/Account/fields/Has_Approved_Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>Has_Approved_Account_Plan__c</fullName>
    <defaultValue>false</defaultValue>
    <description>至少填過一份年度經營計劃</description>
    <label>有過覆核經營計畫</label>
    <type>Checkbox</type>
</CustomField>

code/force-app/main/default/objects/Account/fields/Identification_Type__c.field-meta.xml
<CustomField>
    <fullName>Identification_Type__c</fullName>
    <label>客戶統編類型</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ID_Type</valueSetName>
    </valueSet>
</CustomField>

code/force-app/main/default/objects/Account/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <defaultValue>false</defaultValue>
    <label>授信戶</label>
    <type>Checkbox</type>
</CustomField>

code/force-app/main/default/globalValueSets/CUB_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>TW</fullName>
    </customValue>
    <customValue>
        <fullName>VN</fullName>
    </customValue>
    <customValue>
        <fullName>MY</fullName>
    </customValue>
    <customValue>
        <fullName>HK</fullName>
    </customValue>
    <customValue>
        <fullName>SG</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>PH</fullName>
    </customValue>
    <customValue>
        <fullName>MM</fullName>
    </customValue>
    <masterLabel>國泰據點國別</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

code/force-app/main/default/globalValueSets/ID_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>11</fullName>
        <label>11-身分證統一編號</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>12-外國自然人(舊式編碼)</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>13-內政部配賦統一證號(港澳)</label>
    </customValue>
    <customValue>
        <fullName>14</fullName>
        <label>14-內政部配賦統一證號</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>21-營利事業統一編號(本國)</label>
    </customValue>
    <customValue>
        <fullName>22</fullName>
        <label>22-營利事業統一編號(外國)</label>
    </customValue>
    <customValue>
        <fullName>24</fullName>
        <label>24-扣繳編號/稅籍編號</label>
    </customValue>
    <customValue>
        <fullName>25</fullName>
        <label>25-CUB集團ID</label>
    </customValue>
    <customValue>
        <fullName>31</fullName>
        <label>31-放款虛擬ID</label>
    </customValue>
    <customValue>
        <fullName>32</fullName>
        <label>32-建商編號(放款虛擬ID)</label>
    </customValue>
    <customValue>
        <fullName>38</fullName>
        <label>38-海外分行自然人</label>
    </customValue>
    <customValue>
        <fullName>39</fullName>
        <label>39-海外分行法人</label>
    </customValue>
    <customValue>
        <fullName>88</fullName>
        <label>88-SF CRM 潛客(自然人)</label>
    </customValue>
    <customValue>
        <fullName>89</fullName>
        <label>89-SF CRM 潛客(法人)</label>
    </customValue>
    <masterLabel>客戶統編類型</masterLabel>
</GlobalValueSet>

code/force-app/main/default/classes/Test_FirstAccountPlanTask.cls
@IsTest
public class Test_FirstAccountPlanTask {
	@TestSetup
    public static void SetupData(){
        Account acc = new Account();
        acc.Name = 'Account Test';
        acc.Earliest_NonCredit_Date__c = system.today().addMonths(3);
        acc.Has_Approved_Account_Plan__c = false;
        acc.Loan__c = false;
        acc.Customer_Data_Country__c = 'TW';
        acc.Customer_ID__c = '123456789';
        acc.Identification_Type__c = '21';
        
        insert acc;
    }
    
    @IsTest
    public static void FirstAccountPlanTask(){
        Test.startTest();
        // The schedulable also covers the batch
        System.Schedule('FirstAccountPlanTaskSchedulable','0 0 13 * * ?', new FirstAccountPlanTaskSchedulable());
        Test.stopTest();
    }
}