code/force-app/main/default/objects/Account/fields/Customer_Data_Country__c.field-meta.xml
<CustomField>
    <fullName>Customer_Data_Country__c</fullName>
    <label>客戶資料國別</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CUB_Country</valueSetName>
    </valueSet>
</CustomField>

code/force-app/main/default/objects/Account/fields/Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_ID__c</fullName>
    <externalId>true</externalId>
    <label>客戶 ID</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

code/force-app/main/default/objects/Account/fields/Identification_Type__c.field-meta.xml
<CustomField>
    <fullName>Identification_Type__c</fullName>
    <label>客戶統編類型</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ID_Type</valueSetName>
    </valueSet>
</CustomField>

code/force-app/main/default/objects/Account/fields/PreOccupy_End_Date__c.field-meta.xml
<CustomField>
    <fullName>PreOccupy_End_Date__c</fullName>
    <label>預佔結束日期</label>
    <type>Date</type>
</CustomField>

code/force-app/main/default/objects/Account/fields/Release_Date__c.field-meta.xml
<CustomField>
    <fullName>Release_Date__c</fullName>
    <formula>PreOccupy_End_Date__c +1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>釋出日期</label>
    <type>Date</type>
</CustomField>

code/force-app/main/default/objects/Account/fields/Responsible_RM__c.field-meta.xml
<CustomField>
    <fullName>Responsible_RM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>開發中 RM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

code/force-app/main/default/globalValueSets/CUB_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>TW</fullName>
    </customValue>
    <customValue>
        <fullName>VN</fullName>
    </customValue>
    <customValue>
        <fullName>MY</fullName>
    </customValue>
    <customValue>
        <fullName>HK</fullName>
    </customValue>
    <customValue>
        <fullName>SG</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>PH</fullName>
    </customValue>
    <customValue>
        <fullName>MM</fullName>
    </customValue>
    <masterLabel>國泰據點國別</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

code/force-app/main/default/globalValueSets/ID_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>11</fullName>
        <label>11-身分證統一編號</label>
    </customValue>
    <customValue>
        <fullName>12</fullName>
        <label>12-外國自然人(舊式編碼)</label>
    </customValue>
    <customValue>
        <fullName>13</fullName>
        <label>13-內政部配賦統一證號(港澳)</label>
    </customValue>
    <customValue>
        <fullName>14</fullName>
        <label>14-內政部配賦統一證號</label>
    </customValue>
    <customValue>
        <fullName>21</fullName>
        <label>21-營利事業統一編號(本國)</label>
    </customValue>
    <customValue>
        <fullName>22</fullName>
        <label>22-營利事業統一編號(外國)</label>
    </customValue>
    <customValue>
        <fullName>24</fullName>
        <label>24-扣繳編號/稅籍編號</label>
    </customValue>
    <customValue>
        <fullName>25</fullName>
        <label>25-CUB集團ID</label>
    </customValue>
    <customValue>
        <fullName>31</fullName>
        <label>31-放款虛擬ID</label>
    </customValue>
    <customValue>
        <fullName>32</fullName>
        <label>32-建商編號(放款虛擬ID)</label>
    </customValue>
    <customValue>
        <fullName>38</fullName>
        <label>38-海外分行自然人</label>
    </customValue>
    <customValue>
        <fullName>39</fullName>
        <label>39-海外分行法人</label>
    </customValue>
    <customValue>
        <fullName>88</fullName>
        <label>88-SF CRM 潛客(自然人)</label>
    </customValue>
    <customValue>
        <fullName>89</fullName>
        <label>89-SF CRM 潛客(法人)</label>
    </customValue>
    <masterLabel>客戶統編類型</masterLabel>
</GlobalValueSet>

code/force-app/main/default/classes/Test_ReservedRelease.cls
@isTest
private class Test_ReservedRelease {

    @isTest
    static void myUnitTest() {
        Account account = new Account();
        account.recordtypeId = '012H3000000oqvUIAQ';
        account.Name = '法人D';
		account.customer_ID__c = '11112222';
        account.responsible_RM__c = '005H3000001OwZzIAK';
        account.Identification_Type__c = '21-營利事業統一編號(本國)';
        account.Customer_Data_Country__c = 'TW';
        account.preOccupy_End_Date__c = Date.newInstance(2024, 7, 14);

        insert account;

        Test.startTest();
        ReservedRelease rr = new ReservedRelease();
        Id batchId = Database.executeBatch(rr);
        Test.stopTest();

        Account assertAccount = [SELECT Id, Release_Date__c,Responsible_RM__c FROM Account WHERE Name = '法人D' LIMIT 1];
        System.assertEquals(assertAccount.Responsible_RM__c, null, 'Assertion failed!');
        System.assertEquals(assertAccount.Release_Date__c, null, 'Assertion failed!');
    }
}