code/force-app/main/default/objects/Account/fields/Managed_RM__c.field-meta.xml
<CustomField>
    <fullName>Managed_RM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>經管 RM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

code/force-app/main/default/objects/Account/fields/Release_Date__c.field-meta.xml
<CustomField>
    <fullName>Release_Date__c</fullName>
    <formula>PreOccupy_End_Date__c +1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>釋出日期</label>
    <type>Date</type>
</CustomField>

code/force-app/main/default/objects/Account/fields/Responsible_RM__c.field-meta.xml
<CustomField>
    <fullName>Responsible_RM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>開發中 RM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

code/force-app/main/default/objects/User/fields/Belong_Country__c.field-meta.xml
<CustomField>
    <fullName>Belong_Country__c</fullName>
    <label>隸屬國家</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CUB_Country</valueSetName>
    </valueSet>
</CustomField>

code/force-app/main/default/globalValueSets/CUB_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>TW</fullName>
    </customValue>
    <customValue>
        <fullName>VN</fullName>
    </customValue>
    <customValue>
        <fullName>MY</fullName>
    </customValue>
    <customValue>
        <fullName>HK</fullName>
    </customValue>
    <customValue>
        <fullName>SG</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>PH</fullName>
    </customValue>
    <customValue>
        <fullName>MM</fullName>
    </customValue>
    <masterLabel>國泰據點國別</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

code/force-app/main/default/classes/ReservedRelease.cls
global with sharing class ReservedRelease implements Database.Batchable<SObject>{
    public ReservedRelease() {

    }

    public Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator('SELECT Id, Name, Release_Date__c, Responsible_RM__c, Responsible_RM__r.Belong_Country__c, Responsible_RM__r.Email  FROM Account WHERE Release_Date__c = Today AND Managed_RM__c = null');
    }

    public void execute(Database.BatchableContext bc, List<Account> accounts){
        List<CustomNotificationType> customNotificationTypeDetail = [SELECT Id, DeveloperName FROM CustomNotificationType WHERE  DeveloperName= 'Account_RM_Reserved_Release' LIMIT 1];
        // List<EmailTemplate> emailTemplates = [SELECT Id,Subject, Body FROM EmailTemplate WHERE DeveloperName = 'OccupyAccount_Released_Eng' OR DeveloperName = 'OccupyAccount_Released_TW' ORDER BY Subject DESC];
        List<Messaging.SingleEmailMessage> allmsg = new List<Messaging.SingleEmailMessage>();
        String enNotification = System.Label.get('','Released_Notification','en');
        String zhNotification = System.Label.get('','Released_Notification','zh');
        String enEmail = System.Label.get('','OccupyAccount_Released','en');
        String zhEmail = System.Label.get('','OccupyAccount_Released','zh');

        for(Account account : accounts){
            if(account.Release_Date__c == Date.today()){

                String title;
                String notificationBody;
                String eamilBody;

                if (account.Responsible_RM__r.Belong_Country__c == 'TW') {
                    title = '預佔客戶已釋出';
                    notificationBody =  account.Name + zhNotification;
                    eamilBody = zhEmail; 
                } else {
                    title = 'occupy account has been released';
                    notificationBody =  account.Name + enNotification;
                    eamilBody = enEmail;  
                }

                 // Send Notification
                 Messaging.CustomNotification currNotification = new Messaging.CustomNotification();
                 currNotification.setTitle(title);
                 currNotification.setBody(notificationBody);
                 currNotification.setNotificationTypeId(customNotificationTypeDetail.isEmpty() ? null : customNotificationTypeDetail[0].Id);
                 currNotification.setTargetId(account.Id);
                //  currNotification.send(new Set<String> {account.Responsible_RM__c});
                 
                try {
                    currNotification.send(new Set<String> {account.Responsible_RM__c});
                } catch (Exception ex) {
                    System.debug('Notification Failed: ' + ex.getMessage());
                }

                // Send Email
                String fullRecordURL = URL.getOrgDomainURL().toExternalForm() + '/' + account.Id;
                if(account.Responsible_RM__r.Email != null){
                    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                    mail.setToAddresses(new List<String>{ account.Responsible_RM__r.Email });
                    mail.setHTMLBody(eamilBody + fullRecordURL);
                    mail.setSubject(title);
                    mail.setUseSignature(false);
                    allmsg.add(mail);
                }

                account.Responsible_RM__c = null;

            }
        }  

        try {
            Messaging.sendEmail(allmsg,false);
        } catch (Exception e) {
            System.debug(e.getMessage());
        }
        update accounts;
    }

    public void finish(Database.BatchableContext bc){
        System.debug('finish');
    }
}